apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-probe-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: status-probe-operator
  template:
    metadata:
      labels:
        name: status-probe-operator
    spec:
      serviceAccountName: status-probe-operator
      containers:
        - name: status-probe-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - status-probe-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "status-probe-operator"
